name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  java-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.8

      - name: Build & Run Java tests
        run: ./gradlew build assembleAndroidTest

      - name: Junit Report to Annotations
        uses: turpif/junit-report-annotations-action@v2.0.1
        if: failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          name: "Java JUnit Report"

      - name: Upload JUnit report
        uses: actions/upload-artifact@main
        if: failure()
        with:
          name: junit-report
          path: "**/build/reports/tests"

  android-tests:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - api: '29'
            abi: 'x86'
            tag: 'google_apis'

          - api: '30'
            abi: 'x86'
            tag: 'google_apis'

          - api: '31'
            abi: 'x86_64'
            tag: 'google_apis'

          # api 32 is an interim release of Android without api changes, so it is skipped here

          - api: '33'
            abi: 'x86_64'
            tag: 'playstore'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run all Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api }}
          target: ${{ matrix.tag }}
          arch: ${{ matrix.abi }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -noaudio -no-boot-anim -skin 360x640
          disable-animations: true
          script: |
            adb logcat -c # clear logs
            mkdir artifacts && touch artifacts/logcat.log && chmod +w artifacts/logcat.log
            adb logcat >> artifacts/logcat.log &
            ./gradlew gordon

      - name: Upload logcat output
        uses: actions/upload-artifact@main
        if: failure()
        with:
          name: logcat-${{ matrix.api }}
          path: artifacts/logcat.log

      - name: Junit Report to Annotations
        uses: turpif/junit-report-annotations-action@v2.0.1
        if: failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          name: "Android JUnit Report (API ${{ matrix.api }})"

      - name: Upload JUnit report
        uses: actions/upload-artifact@main
        if: failure()
        with:
          name: junit-report-${{ matrix.api }}
          path: "**/build/reports"

  deploy-development-artifacts:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    needs:
      - java-tests
      - android-tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.8

      - name: Deploy artifacts
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_SECRING_GPG_BASE64: ${{ secrets.MAVEN_SECRING_GPG_BASE64 }}
          MAVEN_SECRING_PASSWORD: ${{ secrets.MAVEN_SECRING_PASSWORD }}
        run: ./gradlew publishReleasePublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository sendReleaseDeployedToSonatypeMessageToSlack